name: Deploy Docs

on:
  push:
    branches:
      - master  # Trigger deployment only on pushes to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure Node 20 matches your local version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          cd docs-site
          npm ci  # clean install using package-lock.json

      # Step 4: Build the documentation
      - name: Build Docs
        run: |
          cd docs-site
          npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs-site/build
